<?php
/**
 * AddressEditTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BurgerDigital\BlackbaudPhpSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Constituent
 *
 * This API manages constituent information and related entities such as addresses, phones, emails, and notes.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BurgerDigital\BlackbaudPhpSdk;

/**
 * AddressEditTest Class Doc Comment
 *
 * @category    Class
 * @description Addresses store information about constituent residences and other addresses along with information about where or whether to send mail.
 * @package     BurgerDigital\BlackbaudPhpSdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressEditTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddressEdit"
     */
    public function testAddressEdit()
    {
    }

    /**
     * Test attribute "address_lines"
     */
    public function testPropertyAddressLines()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "county"
     */
    public function testPropertyCounty()
    {
    }

    /**
     * Test attribute "do_not_mail"
     */
    public function testPropertyDoNotMail()
    {
    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "preferred"
     */
    public function testPropertyPreferred()
    {
    }

    /**
     * Test attribute "seasonal_end"
     */
    public function testPropertySeasonalEnd()
    {
    }

    /**
     * Test attribute "seasonal_start"
     */
    public function testPropertySeasonalStart()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "suburb"
     */
    public function testPropertySuburb()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "information_source"
     */
    public function testPropertyInformationSource()
    {
    }

    /**
     * Test attribute "lot"
     */
    public function testPropertyLot()
    {
    }

    /**
     * Test attribute "cart"
     */
    public function testPropertyCart()
    {
    }

    /**
     * Test attribute "dpc"
     */
    public function testPropertyDpc()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }
}
