<?php
/**
 * GiftApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BurgerDigital\BlackbaudPhpSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Constituent
 *
 * This API manages constituent information and related entities such as addresses, phones, emails, and notes.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BurgerDigital\BlackbaudPhpSdk;

use BurgerDigital\BlackbaudPhpSdk\Configuration;
use BurgerDigital\BlackbaudPhpSdk\ApiException;
use BurgerDigital\BlackbaudPhpSdk\ObjectSerializer;

/**
 * GiftApiTest Class Doc Comment
 *
 * @category Class
 * @package  BurgerDigital\BlackbaudPhpSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GiftApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getConstituentGiftFirst
     *
     * First gift (Get).
     *
     */
    public function testGetConstituentGiftFirst()
    {
    }

    /**
     * Test case for getConstituentGiftGreatest
     *
     * Greatest gift (Get).
     *
     */
    public function testGetConstituentGiftGreatest()
    {
    }

    /**
     * Test case for getConstituentGiftLatest
     *
     * Latest gift (Get).
     *
     */
    public function testGetConstituentGiftLatest()
    {
    }

    /**
     * Test case for getConstituentGivingSummaryLifetime
     *
     * Lifetime giving (Get).
     *
     */
    public function testGetConstituentGivingSummaryLifetime()
    {
    }
}
