<?php
/**
 * PhoneApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BurgerDigital\BlackbaudPhpSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Constituent
 *
 * This API manages constituent information and related entities such as addresses, phones, emails, and notes.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BurgerDigital\BlackbaudPhpSdk;

use BurgerDigital\BlackbaudPhpSdk\Configuration;
use BurgerDigital\BlackbaudPhpSdk\ApiException;
use BurgerDigital\BlackbaudPhpSdk\ObjectSerializer;

/**
 * PhoneApiTest Class Doc Comment
 *
 * @category Class
 * @package  BurgerDigital\BlackbaudPhpSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PhoneApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createConstituentPhone
     *
     * Phone (Create).
     *
     */
    public function testCreateConstituentPhone()
    {
    }

    /**
     * Test case for deleteConstituentPhone
     *
     * Phone (Delete).
     *
     */
    public function testDeleteConstituentPhone()
    {
    }

    /**
     * Test case for editConstituentPhone
     *
     * Phone (Edit).
     *
     */
    public function testEditConstituentPhone()
    {
    }

    /**
     * Test case for getConstituentPhone
     *
     * Phone (Get).
     *
     */
    public function testGetConstituentPhone()
    {
    }

    /**
     * Test case for listConstituentPhonesAllConstituents
     *
     * Phone list (All constituents).
     *
     */
    public function testListConstituentPhonesAllConstituents()
    {
    }

    /**
     * Test case for listConstituentPhonesSingleConstituent
     *
     * Phone list (Single constituent).
     *
     */
    public function testListConstituentPhonesSingleConstituent()
    {
    }

    /**
     * Test case for listPhoneTypes
     *
     * Phone types.
     *
     */
    public function testListPhoneTypes()
    {
    }
}
